### ISSUE TITLE
SARIF export misses required field

### ISSUE THREAD

**Issue by wadoon** [tomasbjerre/violations-command-line#7]
The current `npm` version of `violations-command-line` does not produce valid SARIF files. 

Tested in a [github workflow](https://github.com/wadoon/key-playground/actions/runs/3920319346/jobs/6701873392).

Steps: 

1. Via `gradle pmdMain` I create multiple PMD reports as XML files
2. I use `violations-command-line for the translation into a SARIF file: 
```
npx violations-command-line -sarif pmd-report.json -pv false \
  -v "PMD" "." ".*/build/reports/pmd/main.xml$" "PMD"            \
  -diff-from 0555983bdeefcf7cd7d4eca70068a8a94513aaa2
```
3. On upload to Github codeql I receive a message about missing fields: 
```
...
Error details: instance.runs[0].results[0].kind is not one of enum values: notApplicable,pass,fail,review,open,informational
Error details: instance.runs[0].results[0].level is not one of enum values: none,note,warning,error
...
```

**Comment by tomasbjerre** [comment]
Hopefully fixed with:
https://github.com/tomasbjerre/violations-lib/commit/049738a1ecb37ca

I released 1.22.4 of this tool now.

**Comment by tomasbjerre** [comment]
Works for me now:
https://github.com/tomasbjerre/git-changelog-lib/security/code-scanning/64

**Comment by wadoon** [comment]
Thank you. It works now.
